# Generated by Django 5.2.12 on 2026-05-05 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diyprojects', '0003_project_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='creator',
        ),
    ]
