# Generated by Django 5.2.12 on 2026-05-05 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diyprojects', '0005_project_creator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='profle',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='projectrating',
            old_name='profile',
            new_name='user',
        ),
    ]
