# Generated by Django 6.0.1 on 2026-05-07 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_role_alter_profile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(blank=True, choices=[('Market Seller', 'Market Seller'), ('Event Organizer', 'Event Organizer'), ('Book Contributor', 'Book Contributor'), ('Project Creator', 'Project Creator'), ('Commission Maker', 'Commission Maker')], max_length=255, null=True),
        ),
    ]
