# Generated by Django 6.0.1 on 2026-05-07 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_role_alter_profile_email'),
        ('bookclub', '0003_alter_book_options_book_available_to_borrow_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='borrow',
            old_name='date_returned',
            new_name='date_to_return',
        ),
        migrations.AlterField(
            model_name='bookreview',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book_reviews', to='bookclub.book'),
        ),
        migrations.AlterField(
            model_name='bookreview',
            name='userReviewer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book_reviews', to='accounts.profile'),
        ),
    ]
