# Generated by Django 6.0.2 on 2026-05-06 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0002_commission_maker_commission_status_commission_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['status', '-manpower_required', 'role']},
        ),
        migrations.AlterModelOptions(
            name='jobapplication',
            options={'ordering': ['status', '-applied_on']},
        ),
        migrations.AlterField(
            model_name='commission',
            name='status',
            field=models.CharField(choices=[('1_OPEN', 'Open'), ('2_FULL', 'Full'), ('3_COMPLETED', 'Completed'), ('4_DISCONTINUED', 'Discontinued')], default='1_OPEN', max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('1_OPEN', 'Open'), ('2_FULL', 'Full')], default='1_OPEN', max_length=10),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('1_PENDING', 'Pending'), ('2_ACCEPTED', 'Accepted'), ('3_REJECTED', 'Rejected')], default='1_PENDING', max_length=10),
        ),
    ]
