# Generated by Django 6.0.2 on 2026-05-07 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0003_alter_job_options_alter_jobapplication_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('1_OPEN', 'Open'), ('2_FULL', 'Full')], default='1_OPEN', max_length=20),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('1_PENDING', 'Pending'), ('2_ACCEPTED', 'Accepted'), ('3_REJECTED', 'Rejected')], default='1_PENDING', max_length=20),
        ),
    ]
